version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: zbh
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: notebook
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432